### ISSUE TITLE
Erro de inconsistencia de shapes

### ISSUE THREAD

**Issue by vic37get** [LordWaif/al_module#2]
mples.
  warnings.warn(
(144, 7) <class 'scipy.sparse._csr.csr_matrix'>
Traceback (most recent call last):
  File "main.py", line 74, in <module>
    metricas_teste = calcule_metrics(metricas_teste,teste.y,csr_teste,proba_teste,-1)
  File "/var/projetos/Jupyterhubstorage/victor.silva/al_module/metrics.py", line 18, in calcule_metrics
    metricas['acc'].append(accuracy_score(y_true,y_pred))
  File "/var/projetos/Jupyterhubstorage/victor.silva/al_module/venv/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "/var/projetos/Jupyterhubstorage/victor.silva/al_module/venv/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 223, in accuracy_score
    differing_labels = count_nonzero(y_true - y_pred, axis=1)
  File "/var/projetos/Jupyterhubstorage/victor.silva/al_module/venv/lib/python3.8/site-packages/scipy/sparse/_base.py", line 490, in __sub__
    raise ValueError("inconsistent shapes")
ValueError: inconsistent shapes

**Comment by LordWaif** [comment]
Os dados devem estar em label encoder para passagem da função list_to_csr, além disso bugs na quantidade de classes planejadas
